import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import { ThemeProvider } from "@/components/theme/theme-provider";
import LayoutSidebar from "@/components/sidebar";
import { ModalProvider } from "@/context/modal-provider";
import { OfferSourceProvider } from "@/context/offer-provider";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModalProvider>
            <OfferSourceProvider>
              <LayoutSidebar>{children}</LayoutSidebar>
            </OfferSourceProvider>
          </ModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
